# ANN on binary classification

Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
import tensorflow as tf

In [3]:
tf.__version__

'2.3.0'

Importing the dataset

In [4]:
# Datasetet är orginellt nedladdat från:
# https://www.kaggle.com/ronitf/heart-disease-uci
# 
dataset = pd.read_csv("heart.csv")

In [5]:
dataset.head()

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [6]:
dataset.tail()

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
298   57    0   0       140   241    0  ...      1      0.2      1   0     3       0
299   45    1   3       110   264    0  ...      0      1.2      1   0     3       0
300   68    1   0       144   193    1  ...      0      3.4      1   2     3       0
301   57    1   0       130   131    0  ...      1      1.2      1   1     3       0
302   57    0   1       130   236    0  ...      0      0.0      1   1     2       0

[5 rows x 14 columns]

In [7]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [8]:
X.shape, y.shape

((303, 13), (303,))

Splitting the dataset into Training set and Test set

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state = 0)

In [10]:
X_train.shape, y_train.shape

((242, 13), (242,))

In [11]:
X_test.shape, y_test.shape

((61, 13), (61,))

Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [13]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
X_train

array([[-1.32773282, -1.43641607,  0.98584243, ..., -0.66169316,
        -0.70710678, -0.46472917],
       [ 1.24903178, -1.43641607,  0.98584243, ..., -0.66169316,
         0.26516504, -0.46472917],
       [ 0.35276583,  0.69617712,  0.98584243, ...,  0.95577901,
        -0.70710678, -0.46472917],
       ...,
       [ 0.12869935,  0.69617712,  1.94013791, ..., -0.66169316,
        -0.70710678,  1.14190596],
       [-0.87959984,  0.69617712,  0.98584243, ...,  0.95577901,
        -0.70710678, -0.46472917],
       [ 0.35276583,  0.69617712,  0.03154696, ..., -0.66169316,
        -0.70710678, -0.46472917]])

## Building the ANN

Initializing the ANN

In [15]:
ann = tf.keras.models.Sequential()

Adding the  input layer and the first layer

In [16]:
ann.add(tf.keras.layers.Dense(units=8, activation="relu"))

Adding the second hidden layer

In [17]:
ann.add(tf.keras.layers.Dense(units=8, activation="relu"))

Adding the third hidden layer

In [18]:
ann.add(tf.keras.layers.Dense(units=8, activation="relu"))

Adding the output layer

In [19]:
ann.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

## Training the ANN

Compiling the ANN

In [20]:
ann.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

Training the ANN on the Training set

In [21]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
8/8 [==============================] - 0s 2ms/step - loss: 0.7699 - accuracy: 0.5372
Epoch 2/100
8/8 [==============================] - 0s 2ms/step - loss: 0.7471 - accuracy: 0.5289
Epoch 3/100
8/8 [==============================] - 0s 2ms/step - loss: 0.7316 - accuracy: 0.5289
Epoch 4/100
8/8 [==============================] - 0s 2ms/step - loss: 0.7179 - accuracy: 0.5165
Epoch 5/100
8/8 [==============================] - 0s 2ms/step - loss: 0.7065 - accuracy: 0.5000
Epoch 6/100
8/8 [==============================] - 0s 2ms/step - loss: 0.6973 - accuracy: 0.4876
Epoch 7/100
8/8 [==============================] - 0s 2ms/step - loss: 0.6879 - accuracy: 0.5124
Epoch 8/100
8/8 [==============================] - 0s 2ms/step - loss: 0.6814 - accuracy: 0.5207
Epoch 9/100
8/8 [==============================] - 0s 2ms/step - loss: 0.6734 - accuracy: 0.5579
Epoch 10/100
8/8 [==============================] - 0s 2ms/step - loss: 0.6662 - accuracy: 0.6074
Epoch 11/100
8/8 [===========

## Making the predictions and evaluating the model

Predicting the Test set results

In [22]:
y_pred = ann.predict(X_test)

In [23]:
y_pred.shape

(61, 1)

In [24]:
y_pred = (y_pred > 0.5)

In [25]:
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]]


Making the Confusion Matrix

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [27]:
cm = confusion_matrix(y_test, y_pred)

In [28]:
print(cm)

[[21  6]
 [ 3 31]]


In [29]:
accuracy_score(y_test, y_pred)

0.8524590163934426